// Complete cuisine type mapping from Google Places to our system
export const cuisineTypeMap: Record<string, string> = {
  // Direct mappings - prioritize more specific types first
  'american_restaurant': 'American',
  'chinese_restaurant': 'Chinese',
  'italian_restaurant': 'Italian',
  'indian_restaurant': 'South Asian',
  'pakistani_restaurant': 'South Asian',
  'bangladeshi_restaurant': 'South Asian',
  'sri_lankan_restaurant': 'South Asian',
  'nepali_restaurant': 'South Asian',
  'japanese_restaurant': 'Japanese',
  'korean_restaurant': 'Korean',
  'mexican_restaurant': 'Mexican',
  'thai_restaurant': 'Thai',
  'vietnamese_restaurant': 'Vietnamese',
  'mediterranean_restaurant': 'Mediterranean',
  'middle_eastern_restaurant': 'Middle Eastern',
  'lebanese_restaurant': 'Middle Eastern',
  'persian_restaurant': 'Middle Eastern',
  'iranian_restaurant': 'Middle Eastern',
  'afghan_restaurant': 'Middle Eastern',
  'syrian_restaurant': 'Middle Eastern',
  'iraqi_restaurant': 'Middle Eastern',
  'jordanian_restaurant': 'Middle Eastern',
  'palestinian_restaurant': 'Middle Eastern',
  'yemeni_restaurant': 'Middle Eastern',
  'turkish_restaurant': 'Turkish',
  'greek_restaurant': 'Mediterranean',
  'moroccan_restaurant': 'Middle Eastern',
  'egyptian_restaurant': 'Middle Eastern',
  'tunisian_restaurant': 'Middle Eastern',
  'algerian_restaurant': 'Middle Eastern',
  'seafood_restaurant': 'Seafood',
  'steak_house': 'American',
  'pizza_restaurant': 'Italian',
  'fast_food_restaurant': 'Fast Food',
  'cafe': 'Cafe',
  'coffee_shop': 'Cafe',
  'bakery': 'Bakery',
  'bar': 'Bar & Grill',
  'bar_and_grill': 'Bar & Grill',
  'brunch_restaurant': 'Brunch',
  'breakfast_restaurant': 'Breakfast',
  'hamburger_restaurant': 'American',
  'sandwich_shop': 'Deli',
  'deli': 'Deli',
  'ice_cream_shop': 'Dessert',
  'dessert_shop': 'Dessert',
  'french_restaurant': 'French',
  'spanish_restaurant': 'Spanish',
  'brazilian_restaurant': 'Latin American',
  'latin_american_restaurant': 'Latin American',
  'caribbean_restaurant': 'Caribbean',
  'african_restaurant': 'African',
  'ethiopian_restaurant': 'African',
  'nigerian_restaurant': 'African',
  'somali_restaurant': 'African',
  'indonesian_restaurant': 'Southeast Asian',
  'malaysian_restaurant': 'Southeast Asian',
  'singaporean_restaurant': 'Southeast Asian',
  'filipino_restaurant': 'Southeast Asian',
  'sushi_restaurant': 'Japanese',
  'ramen_restaurant': 'Japanese',
  'dim_sum_restaurant': 'Chinese',
  'noodle_restaurant': 'Asian',
  'asian_restaurant': 'Asian',
  'bbq_restaurant': 'BBQ',
  'barbecue_restaurant': 'BBQ',
  'chicken_restaurant': 'American',
  'chicken_shop': 'American',
  'wings_restaurant': 'American',
  'fried_chicken_restaurant': 'American',
  'food_court': 'Food Court',
  'buffet_restaurant': 'Buffet',
  'fine_dining_restaurant': 'Fine Dining',
  'vegan_restaurant': 'Vegan',
  'vegetarian_restaurant': 'Vegetarian',
  'soul_food_restaurant': 'Soul Food',
  'southern_restaurant': 'Southern',
  'tex_mex_restaurant': 'Mexican',
  'taco_restaurant': 'Mexican',
  'burrito_restaurant': 'Mexican',
  'poke_restaurant': 'Hawaiian',
  'hawaiian_restaurant': 'Hawaiian',
  'halal_restaurant': 'Halal',
  'halal': 'Halal',
  'kosher_restaurant': 'Kosher',
  'food': 'Other',
  'restaurant': 'Other',
  'meal_delivery': 'Delivery',
  'meal_takeaway': 'Takeaway',
  // Additional variations Google might return
  'halal_food': 'Halal',
  'halal food': 'Halal',
  'Halal restaurant': 'Halal',
  'Halal Restaurant': 'Halal',
};
